.mode columns
.headers on 
--
--SELECT A.ID1, A2.ID2
--FROM Estudante E1 INNER JOIN Amizade A
--ON E1.ID = A.ID1
--INNER JOIN Estudante E2
--ON A.ID2 = E2.ID
--INNER JOIN Amizade A2
--ON E2.ID = A2.ID1
--INNER JOIN Estudante E3
--ON A2.ID2 = E3.ID
--WHERE A.ID1 <> A2.ID2 
--AND A.ID1 NOT IN (
--    SELECT ID1 FROM Amizade Aux1
--    WHERE Aux1.ID1 = A.ID1 AND Aux1.ID2 = A2.ID2)
--AND A2.ID2 NOT IN (
--    SELECT ID2 FROM Amizade Aux1
--    WHERE Aux1.ID1 = A.ID1 AND Aux1.ID2 = A2.ID2)
--ORDER BY A.ID1 ASC, A2.ID2 ASC;


SELECT A1.ID1, A2.ID2
FROM Amizade A1 INNER JOIN Amizade A2
ON A1.ID2 = A2.ID1 AND A1.ID1 < A2.ID2
WHERE A1.ID1 <> A2.ID2 
AND A1.ID1 NOT IN (
    SELECT ID1 FROM Amizade Aux1
    WHERE Aux1.ID1 = A1.ID1 AND Aux1.ID2 = A2.ID2)
AND A2.ID2 NOT IN (
    SELECT ID2 FROM Amizade Aux1
    WHERE Aux1.ID1 = A1.ID1 AND Aux1.ID2 = A2.ID2)
ORDER BY A1.ID1 ASC, A2.ID2 ASC;


--INCOMPLETO