.mode columns 
.headers ON

DROP TRIGGER IF EXISTS Inserts;
DROP TRIGGER IF EXISTS Deletes;
DROP TRIGGER IF EXISTS Updates;

CREATE TRIGGER IF NOT EXISTS Inserts
BEFORE INSERT ON Amizade
BEGIN
    INSERT INTO Amizade VALUES (New.ID2, New.ID1);
END;

CREATE TRIGGER IF NOT EXISTS Deletes
BEFORE DELETE ON Amizade
BEGIN
    DELETE FROM Amizade WHERE ID1 = Old.ID2 AND ID2 = Old.ID1;
END;

CREATE TRIGGER IF NOT EXISTS Updates
BEFORE UPDATE ON Amizade
BEGIN
    SELECT RAISE(ABORT, 'Cant update this table');
END;